version: "1"

services:
  nerfstudio:
    build: .
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ports:
      - 7860:7860
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
        - ./outputs:/outputs
        - ./data:/data